### ISSUE TITLE
Killing Pillar John Crashes the Game

### ISSUE THREAD

**Issue by TheNoiseWoag** [burnedpopcorn/PT-Stuffed-Crust-Web-Port#1]
When killing Pillar John to start Pizza Time, the game crashes. The error says it is due to "obj_camera". It works fine in the tutorial, (yes I did test in the tutorial), but when I went to go play John Gutter the game crashed when killing Pillar John. I don't know if this issue only applies to John Gutter, but I would assume it applies to all levels. I didn't mess with the settings, or adjust the camera at all.

**Comment by HogOfTheHill** [comment]
Are you sure you didn't change any of the modded settings? Since my game usually crashes when having "Panic BG" and/or "Panic Tilt" on
